<?php

namespace Tychovbh\LaravelCrud\Tests;

use Tychovbh\LaravelCrud\Tests\App\Kernel;
use Tychovbh\LaravelCrud\LaravelCrudServiceProvider;
use Tychovbh\LaravelCrud\Tests\App\Routes\PostRoute;
use Tychovbh\LaravelCrud\Tests\App\Routes\UserRoute;
use Tychovbh\LaravelCrud\Tests\App\Routes\PageRoute;

class TestCase extends \Orchestra\Testbench\TestCase
{
    /**
     * Get package providers.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [LaravelCrudServiceProvider::class];
    }

    /**
     * Define environment setup.
     *
     * @param \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        UserRoute::routes();
        PostRoute::routes();
        PageRoute::routes();
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
        $this->withFactories(__DIR__ . '/database/factories');
    }

    /**
     * Resolve application HTTP Kernel implementation.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @return void
     */
    protected function resolveApplicationHttpKernel($app)
    {
        $app->singleton('Illuminate\Contracts\Http\Kernel', Kernel::class);
    }
}
